#!/usr/bin/env bash

host= # Host the server is being deployed to.
wd=   # Working directory to run the server from on the host.

while [ ! $# -eq 0 ]
do
  case "$1" in
    --host | -h)
      host=$2
      ;;
    --working-directory | -wd )
      wd=$2
      ;;
  esac
  shift
done

if [ -z "$host" ]
then
  echo 'must pass host the server is being deployed to'
  exit 1
fi
if [ -z "$wd" ]
then
  echo 'must pass working directory to run the server from on the host'
  exit 1
fi

ssh $host << EOF
cd $wd
rm -rf butler
echo 'cloning'
git clone https://github.com/jwowillo/butler.git > /dev/null 2> /dev/null
echo
echo 'building'
echo
make butler_gen butler_server
echo
cd butler
echo 'killing server if running'
pgrep butler_server | xargs kill 2> /dev/null || true
echo
echo 'starting server'
echo
nohup ./run > /dev/null 2> /dev/null < /dev/null &
EOF
