#!/usr/bin/env python3

"""deploy butler to a host."""

import argparse

import cmd


def deploy(host, directory):
    """deploy butler to the host and make the server run in directory."""
    CMD = '''
cd {}
rm -rf butler
echo 'cloning'
git clone https://github.com/jwowillo/butler.git > /dev/null 2> /dev/null
cd butler
echo 'building'
make butler_gen
go get github.com/jwowillo/gen/cmd/gen_server
echo 'generating'
./run_gen
echo 'checking if server is running'
ID=$(pgrep gen_server)
if [ -z "$ID" ]; then
  echo 'starting server'
  nohup ./run_server > /dev/null 2> /dev/null < /dev/null &
else
  echo 'server already running'
fi
'''
    cmd.ssh(host, CMD.format(directory))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('host', help='host the server is being deployed to')
    parser.add_argument('directory',
                        help='directory to run the server from on the host')
    args = parser.parse_args()
    deploy(args.host, args.directory)

