#!/usr/bin/env bash

web='web'
recipes='book'
directory='build'
debug=false
port=':3000'

while [ ! $# -eq 0 ]
do
  case "$1" in
    --web)
      web=$2
      ;;
    --recipes)
      recipes=$2
      ;;
    --directory)
      directory=$2
      ;;
    --debug)
      if [ -z "$2" ]; then
        debug=true
      else
        debug=$2
      fi
      ;;
    --port)
      port=$2
      echo "$2"
      ;;
  esac
  shift
done

butler_gen --recipes $recipes --web $web --directory $directory --debug=$debug
butler_server --port $port --directory $directory
